#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define CUSTOM_FONT
#define CUSTOM_LAYER_READ
#define SPLIT_TRANSPORT_MIRROR


#define EE_HANDS

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED 17


// #ifdef AUTOCORRECT_ENABLE
// #    define AUTOSHIFT_TIMEOUT 1
// #    define TAP_CODE_DELAY 10
// #endif

#ifdef AUTO_SHIFT_ENABLE
#    define AUTO_SHIFT_TIMEOUT 150
#    define NO_AUTO_SHIFT_SPECIAL
#endif

#define TAPPING_FORCE_HOLD
#ifdef TAPPING_TERM
#    undef TAPPING_TERM
#    define TAPPING_TERM 200
#endif

#ifdef OLED_ENABLE
#    define OLED_TIMEOUT 0
#endif

#ifdef UCIS_ENABLE
#    define UCIS_MAX_CODE_POINTS 55
#    define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
#endif
