# Basic configuration
BOOTLOADER = rp2040
CONSOLE_ENABLE = no
LTO_ENABLE = yes
MCU = kb2040
CONVERT_TO = kb2040
# Display
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
# Encoder
ENCODER_ENABLE = yes
# Features
AUTO_SHIFT_ENABLE = yes
#AUTOCORRECT_ENABLE = yes
#CAPS_WORD_ENABLE = yes
COMBO_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
SEND_STRING_ENABLE = yes
TAP_DANCE_ENABLE = yes
UCIS_ENABLE = yes
#UNICODEMAP_ENABLE = yes
#UNICODE_ENABLE = yes
WPM_ENABLE = yes
# RGB
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
